# Generated by Django 4.2 on 2025-07-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('genre', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Sube una imagen de la película', null=True, upload_to='movies_images')),
            ],
        ),
    ]
